name: repositories
description: Repositories for data access in the hive_note app.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  app_database:
    path: ../app_database
  user_pref:
    path: ../user_pref


dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
