name: drift_database
description: A Flutter implementation of the DBApi that uses sqlite with Drift ORM.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.20.0
  drift_flutter: ^0.1.0
  database:
    path: ../database

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.20.0
  build_runner: ^2.4.12
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
